# This is a basic workflow to help you get started with Actions

name: badge

on:
  push:
    branches:
      - golang
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - uses: shuzijun/leetcode-editor-action@v0.1.1
        with:
          STATISTICS_DIRECTORY: .idea/leetcode-pro/
          LEETCODE_SITE: leetcode.cn

